dist: xenial
language: python
cache: pip

python:
  - "3.7"
  - "3.8"

install:
  - git clone https://github.com/duysqubix/evennia.git ../evennia
  - pip install -e ../evennia
  - pip install -r requirements.txt

script:
  - evennia test --settings settings.py .