name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: "Install dependencies"
        run: |
          git clone https://github.com/duysqubix/evennia.git ../evennia
          python -m pip install --upgrade pip
          pip install -e ../evennia
          pip install -r requirements.txt
      
      - name: Test Scrolls
        run: |
           evennia makemigrations && evennia migrate
           evennia test --settings settings.py .
